[package]
name = "wasi-crypto"
version = "0.1.5"
authors = ["Frank Denis <github@pureftpd.org>"]
edition = "2018"
description = "Experimental implementation of the WASI cryptography APIs"
documentation = "https://docs.rs/wasi-crypto"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm", "cryptography"]
keywords = ["webassembly", "wasm", "crypto"]
repository = "https://github.com/webassembly/wasi-crypto"

[dependencies]
aes-gcm = "0.9.4"
anyhow = "1.0.56"
bincode = "1.3.3"
byteorder = "1.4.3"
chacha20poly1305 = "0.9.0"
curve25519-dalek = "3.2.1"
derivative = "2.2.0"
ed25519-dalek = "1.0.1"
hkdf = "0.12.3"
hmac = "0.12.1"
k256 = { version = "0.10.4", features = ["ecdsa", "std", "zeroize", "pkcs8", "pem"] }
p256 = { version = "0.10.1", features = ["ecdsa", "std", "zeroize", "pkcs8", "pem"] }
parking_lot = "0.12.0"
pqcrypto = { version = "0.14.2", default-features = false, features = ["pqcrypto-kyber"], optional = true }
rand_core = { version = "0.6.3", default-features = false, package = "rand_core" }
rand_core_05 = { package = "rand_core", version = "0.6.3", default-features = false }
rsa = { version = "0.5.0", features = ["serde", "expose-internals"] }
serde = { version = "1.0.136", features = ["derive"] }
sha2 = "0.10.2"
subtle = "2.4.1"
thiserror = "1.0.30"
xoodyak = "0.7.3"
zeroize = "1.5.4"

[features]
default = ["pqcrypto"]

[badges]
maintenance = { status = "experimental" }
